name: Android APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to v4

    - name: Set up JDK
      uses: actions/setup-java@v4  # Updated to v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: APK
        path: android/app/build/outputs/apk/debug/app-debug.apk
